print("Macam-Macam Type Data")
print("Integer ialah bilangan bulat, contoh : 95")
print("Float ialah bilangan yang ada koma, contoh : 8.5")
print("String ialah karakter/kalimat yang berupa angka, contoh : ayo kita makan bareng")
print("Boolean ialah menyatakan benar True jika bernilai 1, atau salah False bernilai 0, contoh : False dan True")